[[plugins]]
repo = "LumaKernel/fern-mapping-fzf.vim"
depends = ["fzf", "fern.vim"]
hook_add = '''
  function! Fern_mapping_fzf_customize_option(spec)
    let a:spec.options .= ' --multi'
    " Note that fzf#vim#with_preview comes from fzf.vim
    return fzf#vim#with_preview(a:spec)
    " if exists('*fzf#vim#with_preview')
    "   return fzf#vim#with_preview(a:spec)
    " else
    "   return a:spec
    " endif
  endfunction
  function! Fern_mapping_fzf_before_all(dict)
    if !len(a:dict.lines)
      return
    endif
    return a:dict.fern_helper.async.update_marks([])
  endfunction
  function! s:reveal(dict)
    execute "FernReveal -wait" a:dict.relative_path
    execute "normal \<Plug>(fern-action-mark:set)"
  endfunction
  let g:Fern_mapping_fzf_file_sink = function('s:reveal')
  let g:Fern_mapping_fzf_dir_sink = function('s:reveal')
'''
# "fern-mapping-fzf.vim": {
#   "lazy": 0,
#   "path": "/Users/fujimotokatsuki/.cache/dein/repos/github.com/LumaKernel/fern-mapping-fzf.vim",
#   "name": "fern-mapping-fzf.vim",
#   "repo": "LumaKernel/fern-mapping-fzf.vim",
#   "hook_add": "  function! Fern_mapping_fzf_customize_option(spec)\n    let a:spec.options .= ' --multi'\n    \" Note that fzf#vim#with_preview comes from fzf.vim\n    return fzf#vim#with_preview(a:spec)\n    \" if exists('*fzf#vim#with_preview')\n    \"   return fzf#vim#with_preview(a:spec)\n    \" else\n    \"   return a:spec\n    \" endif\n  endfunction\n\n  function! Fern_mapping_fzf_before_all(dict)\n    if !len(a:dict.lines)\n      return\n    endif\n    return a:dict.fern_helper.async.update_marks([])\n  endfunction\n\n  function! s:reveal(dict)\n    execute \"FernReveal -wait\" a:dict.relative_path\n    execute \"normal \\<Plug>(fern-action-mark:set)\"\n  endfunction\n\n  let g:Fern_mapping_fzf_file_sink = function('s:reveal')\n  let g:Fern_mapping_fzf_dir_sink = function('s:reveal')\n",
#   "merged": 1,
#   "normalized_name": "fern-mapping-fzf",
#   "type": "git",
#   "rtp": "/Users/fujimotokatsuki/.cache/dein/repos/github.com/LumaKernel/fern-mapping-fzf.vim",
#   "sourced": 1
# },
# "fern-mapping-fzf.vim":{
#   lazy:0,
#   path:"/Users/fujimotokatsuki/.cache/dein/repos/github.com/LumaKernel/fern-mapping-fzf.vim",
#   name:"fern-mapping-fzf.vim",
#   repo:"LumaKernel/fern-mapping-fzf.vim",
#   hook_add:"  function! Fern_mapping_fzf_customize_option(spec)\n    let a:spec.options .= ' --multi'\n    \" Note that fzf#vim#with_preview comes from fzf.vim\n    return fzf#vim#with_preview(a:spec)\n    \" if exists('*fzf#vim#with_preview')\n    \"   return fzf#vim#with_preview(a:spec)\n    \" else\n    \"   return a:spec\n    \" endif\n  endfunction\n\n  function! Fern_mapping_fzf_before_all(dict)\n    if !len(a:dict.lines)\n      return\n    endif\n    return a:dict.fern_helper.async.update_marks([])\n  endfunction\n\n  function! s:reveal(dict)\n    execute \"FernReveal -wait\" a:dict.relative_path\n    execute \"normal \\<Plug>(fern-action-mark:set)\"\n  endfunction\n\n  let g:Fern_mapping_fzf_file_sink = function('s:reveal')\n  let g:Fern_mapping_fzf_dir_sink = function('s:reveal')\n",
#   merged:1,
#   normalized_name:"fern-mapping-fzf",
#   type:"git",
#   rtp:"/Users/fujimotokatsuki/.cache/dein/repos/github.com/LumaKernel/fern-mapping-fzf.vim",
#   sourced:1
# },
