[[plugins]]
repo = "tomasr/molokai"
hook_add = '''
  let g:molokai_original = 1
  let g:rehash256 = 1
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nested を付ける。
  autocmd MyAutoCmd VimEnter * nested colorscheme molokai
  syntax enable
  set background=dark
  set t_Co=256
'''
# "molokai": {
#   "lazy": 0,
#   "path": "/Users/fujimotokatsuki/.cache/dein/repos/github.com/tomasr/molokai",
#   "name": "molokai",
#   "repo": "tomasr/molokai",
#   "hook_add": "  let g:molokai_original = 1\n  let g:rehash256 = 1\n  \" colorscheme 設定は source 後に行う必要があるので VimEnter で行う。\n  \" 但し Colorscheme イベントの発生が抑制されないよう nested を付ける。\n  autocmd MyAutoCmd VimEnter * nested colorscheme molokai\n  syntax enable\n  set background=dark\n  set t_Co=256\n",
#   "merged": 1,
#   "normalized_name": "molokai",
#   "type": "git",
#   "rtp": "/Users/fujimotokatsuki/.cache/dein/repos/github.com/tomasr/molokai",
#   "sourced": 1
# },
# molokai:{
#   lazy:0,
#   path:"/Users/fujimotokatsuki/.cache/dein/repos/github.com/tomasr/molokai",
#   name:"molokai",
#   repo:"tomasr/molokai",
#   hook_add:"  let g:molokai_original = 1\n  let g:rehash256 = 1\n  \" colorscheme 設定は source 後に行う必要があるので VimEnter で行う。\n  \" 但し Colorscheme イベントの発生が抑制されないよう nested を付ける。\n  autocmd MyAutoCmd VimEnter * nested colorscheme molokai\n  syntax enable\n  set background=dark\n  set t_Co=256\n",
#   merged:1,
#   normalized_name:"molokai",
#   type:"git",
#   rtp:"/Users/fujimotokatsuki/.cache/dein/repos/github.com/tomasr/molokai",
#   sourced:1
# },
