[[plugins]]
repo = "tomtom/tcomment_vim"
# "tcomment_vim": {
#   "lazy": 0,
#   "path": "/Users/fujimotokatsuki/.cache/dein/repos/github.com/tomtom/tcomment_vim",
#   "repo": "tomtom/tcomment_vim",
#   "normalized_name": "tcomment",
#   "merged": 1,
#   "type": "git",
#   "rtp": "/Users/fujimotokatsuki/.cache/dein/repos/github.com/tomtom/tcomment_vim",
#   "sourced": 1,
#   "name": "tcomment_vim"
# },
# tcomment_vim:{
#   lazy:0,
#   path:"/Users/fujimotokatsuki/.cache/dein/repos/github.com/tomtom/tcomment_vim",
#   repo:"tomtom/tcomment_vim",
#   normalized_name:"tcomment",
#   merged:1,
#   type:"git",
#   rtp:"/Users/fujimotokatsuki/.cache/dein/repos/github.com/tomtom/tcomment_vim",
#   sourced:1,
#   name:"tcomment_vim"
# },
