[[plugins]]
repo = "thinca/vim-quickrun"
hook_add = '''
  let g:quickrun_config = {'*': {'hook/time/enable': '1', 'split': ''}, }
  noremap <leader>q :QuickRun<CR>
'''
# "vim-quickrun": {
#   "lazy": 0,
#   "path": "/Users/fujimotokatsuki/.cache/dein/repos/github.com/thinca/vim-quickrun",
#   "name": "vim-quickrun",
#   "repo": "thinca/vim-quickrun",
#   "hook_add": "  let g:quickrun_config = {'*': {'hook/time/enable': '1', 'split': ''}, }\n  noremap <leader>q :QuickRun<CR>\n",
#   "merged": 1,
#   "normalized_name": "quickrun",
#   "type": "git",
#   "rtp": "/Users/fujimotokatsuki/.cache/dein/repos/github.com/thinca/vim-quickrun",
#   "sourced": 1
# },
# "vim-quickrun":{
#   lazy:0,
#   path:"/Users/fujimotokatsuki/.cache/dein/repos/github.com/thinca/vim-quickrun",
#   name:"vim-quickrun",
#   repo:"thinca/vim-quickrun",
#   hook_add:"  let g:quickrun_config = {'*': {'hook/time/enable': '1', 'split': ''}, }\n  noremap <leader>q :QuickRun<CR>\n",
#   merged:1,
#   normalized_name:"quickrun",
#   type:"git",
#   rtp:"/Users/fujimotokatsuki/.cache/dein/repos/github.com/thinca/vim-quickrun",
#   sourced:1
# },
