[[plugins]]
repo = "prettier/vim-prettier"
merge = 0
on_ft = ["javascript", "typescript", "vue", "css", "scss", "json", "markdown"]
hook_source = '''
  " @formatアノテーションを持ったファイルの自動フォーマットを無効にする
  let g:prettier#autoformat = 0
  " Prettierのパースエラーをquickfixに表示しない
  let g:prettier#quickfix_enabled = 0
  autocmd BufWritePre *.js,*.ts,*.vue,*.css,*.scss,*.json,*.md PrettierAsync
'''
