[[plugins]]
repo = "yuki-yano/fern-preview.vim"
hook_add = '''
  function! s:fern_settings() abort
    nmap <silent> <buffer> p <Plug>(fern-action-preview:toggle)
  endfunction
  augroup fern-settings
    autocmd!
    autocmd FileType fern call s:fern_settings()
  augroup END
'''
