[[plugins]]
repo = "lambdalisue/fern.vim"
hook_add = '''
  " デフォルトマッピングをオフ
  " let g:fern#disable_default_mappings = 1
  " 隠しファイルの表示
  let g:fern#default_hidden=1
  function! s:init_fern() abort
    nmap <silent> <buffer> <C-v> <Plug>(fern-action-open:vsplit)
    nmap <silent> <buffer> <C-x> <Plug>(fern-action-open:split)
    nmap <silent> <buffer> <C-t> <Plug>(fern-action-open:tabedit)
    " 下記の既にプラグインメソッドに割り振られているキーマップを変更する場合は
    " そのメソッドへのキーマップを変えた上でやる必要がある
    nmap <silent> <buffer> <C-b> <Plug>(fern-action-redraw)
    nmap <silent> <buffer> <C-l> :wincmd l<CR>
    nmap <silent> <buffer> cd <Plug>(fern-action-cd)
    " ディレクトリのアイコンが緑色、ディレクトリ名が赤色になってしまうので上書き
    highlight Directory ctermfg=8 ctermbg=NONE cterm=NONE guifg=#6B7089 guibg=NONE gui=NONE
    highlight FernBranchText ctermfg=8 ctermbg=NONE cterm=NONE guifg=#bbbfc7 guibg=NONE gui=NONE
  endfunction
  augroup fern-custom
    autocmd! *
    autocmd FileType fern call s:init_fern()
  augroup END
  noremap <C-a> :Fern . -reveal=% -drawer -toggle -width=42<CR>
'''
