[[plugins]]
repo = "LumaKernel/fern-mapping-fzf.vim"
depends = ["fzf", "fern.vim"]
hook_add = '''
  function! Fern_mapping_fzf_customize_option(spec)
    let a:spec.options .= ' --multi'
    " Note that fzf#vim#with_preview comes from fzf.vim
    return fzf#vim#with_preview(a:spec)
    " if exists('*fzf#vim#with_preview')
    "   return fzf#vim#with_preview(a:spec)
    " else
    "   return a:spec
    " endif
  endfunction
  function! Fern_mapping_fzf_before_all(dict)
    if !len(a:dict.lines)
      return
    endif
    return a:dict.fern_helper.async.update_marks([])
  endfunction
  function! s:reveal(dict)
    execute "FernReveal -wait" a:dict.relative_path
    execute "normal \<Plug>(fern-action-mark:set)"
  endfunction
  let g:Fern_mapping_fzf_file_sink = function('s:reveal')
  let g:Fern_mapping_fzf_dir_sink = function('s:reveal')
'''

# ff	fzf-files
# fd	fzf-dirs
# fa	fzf-both
# frf	fzf-root-files
# frd	fzf-root-dirs
# fra	fzf-root-both
