[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = '''
  set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}
  let g:lightline = {
        \ 'colorscheme': 'wombat',
        \ 'active': {
          \ 'left': [
            \ [ 'mode', 'paste' ],
            \ [ 'readonly', 'relativepath', 'modified' ],
            \ [ 'gitbranch' ],
            \ [ 'cocstatus' ],
          \ ],
        \ },
        \ 'component_function': {
          \ 'cocstatus': 'coc#status',
          \ 'gitbranch': 'FugitiveHead',
        \ },
      \ }
'''
