[[plugins]]
repo = "tomasr/molokai"
hook_add = '''
  let g:molokai_original = 1
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nested を付ける。
  autocmd VimEnter * nested colorscheme molokai
  syntax enable
  set background=dark
  set t_Co=256
'''
