[[plugins]]
repo = "tpope/vim-surround"

# normal modeの場合（指定記号を変更したい）
## cs{変更前}{変更後}
## 例: cs"'
## ds{削除対象}
## 例: ds"

# visual modeの場合（選択文字列を記号で囲みたい）
## visualで選択 -> S -> 選択
## 例: " / '
## {,[,(などの左側ブラケットだとスペースを含む
## },],)などの右側ブラケットだとスペースを含まない
