[[plugins]]
repo = "tpope/vim-fugitive"
hook_add = '''
  noremap <leader>ga :Git add %:p<CR><CR>
  noremap <leader>gc :Gcommit<CR><CR>
  noremap <leader>gs :Gstatus<CR>
  noremap <leader>gp :Gpush<CR>
  noremap <leader>gd :Gdiff<CR>
  noremap <leader>gl :Glog<CR>
  noremap <leader>gb :Gblame<CR>
'''
