[[plugins]]
repo = "tpope/vim-fugitive"
hook_add = '''
  noremap <leader>ga :Git add %:p<CR><CR>
  noremap <leader>gc :Git commit<CR><CR>
  noremap <leader>gs :Git status<CR>
  noremap <leader>gp :Git push<CR>
  noremap <leader>gd :Git diff<CR>
  noremap <leader>gl :Git log<CR>
  noremap <leader>gb :Git blame<CR>
'''
