[[plugins]]
repo = "nathanaelkane/vim-indent-guides"
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  if has('nvim')
  else
    let g:indent_guides_auto_colors = 0
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=236
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=238
  endif
'''
