[[plugins]]
repo = "easymotion/vim-easymotion"
hook_add = '''
  let g:EasyMotion_do_mapping = 0
  let g:EasyMotion_smartcase = 1
  nmap <leader>s <Plug>(easymotion-s2)
  map <leader>j <Plug>(easymotion-j)
  map <leader>k <Plug>(easymotion-k)
'''
